### PR TITLE
Get working with relay-compiler 1.1.0

### PR DESCRIPTION
**Pull request by danielholmes**
relay-compiler has a few small changes in 1.1.0. I've tested this on a project I'm developing at the moment and it's all working fine, but I'm still pretty new to relay so might have missed some pieces.

### CODE REVIEW

**Comment by coleturner** [comment]
I tried emailing the repo maintainer about this pull request, as the current state of the package dos not work. No response yet.

@danielholmes are you considering namespacing the package?

**Comment by danielholmes** [comment]
@colepatrickturner yea lets do it, I've had some other things I want fixed + improved I've been holding back too. Is there a convention for namespacing packages on npm? e.g. danielholmes-relay-compiler-webpack-plugin ?

**Comment by coleturner** [comment]
Maybe give this a try? I'm not sure either.
https://docs.npmjs.com/getting-started/scoped-packages

**Comment by danielholmes** [comment]
@colepatrickturner done: https://www.npmjs.com/package/@dhau/relay-compiler-webpack-plugin . I've published 0.4.0 which has the above PR merged

**Comment by ryanblakeley** [comment]
@danielholmes Thanks for doing that. You might want to change the README.md to show

```
npm install --save-dev @dhau/relay-compiler-webpack-plugin
```

Edit: npm path

**Pull request closed without merging**
